version: 2
jobs:
  build:
    docker:
      - image: debian:bullseye
    steps:
      - checkout
      - run:
          name: Install Perl packages
          command: apt-get update && apt-get install -y cpanminus make gcc openssl libssl-dev zlib1g-dev git
      - run:
          name: Install dzil
          command: cpanm --notest Dist::Zilla Dist::Zilla::App::Command::cover App::cpm Devel::Cover::Report::Codecov https://cpan.metacpan.org/authors/id/S/SR/SRI/Mojolicious-7.29.tar.gz https://cpan.metacpan.org/authors/id/B/BI/BINGOS/ExtUtils-MakeMaker-7.30.tar.gz
      - run:
          name: Install dzil author deps
          command: cpm install --show-build-log-on-failure -w 2 --mirror=http://cpan.cpantesters.org/ -g $(dzil authordeps --missing)
      - run:
          name: Install Mojo::WebSocketProxy (will delete after Mojo::WebSocketProxy new version released)
          command: cpanm -n git@github.com:chylli-binary/perl-Mojo-WebSocketProxy.git@chylli/spit-module-from-Mojo-WebSocketProxy
      - run:
          name: Install distribution deps
          command: cpm install --show-build-log-on-failure -w 2 --mirror=http://cpan.cpantesters.org/ -g $(dzil listdeps --author --missing)
      - run:
          name: Run smoke test
          command: dzil smoke --release --author
      - run:
          name: Run coverage test
          command: dzil cover -test -report codecov
      - run:
          name: Run extended author test
          command: dzil xtest

